### ISSUE TITLE
Caddy + dumbproxy

### ISSUE THREAD

**Issue by doroved** [SenseUnit/dumbproxy#55]
Hi. I have one VPS and would like to use it to host projects over https and install dumbproxy HTTPS.
Since I can't run >1 container on port 443, is it possible to use a Caddy HTTPS server that will redirect HTTPS traffic to the dumbproxy-https container?
https://caddyserver.com/docs/running#docker-compose

**I'm trying this configuration of Caddyfile:**
```
proxy.mydomain.com {
    reverse_proxy dumbproxy-https:4434
}
```
**Starting dumbproxy:**
```Dockerfile
docker run -d \
    --security-opt no-new-privileges \
    -p 4434:443 \
    --restart unless-stopped \
    --name dumbproxy-https \
    yarmak/dumbproxy -bind-address :443 -auth 'static://?username=***&password=***'
```

**Test command:**
```
curl -v  -x 'https://user:pass@proxy.mydomain.com:443' ifconfig.co
```

I've tried different config combinations when running the dumbproxy container, but nothing works.
I either get an error like this:
```
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```
Or just an empty 200 OK response

**Comment by Snawoot** [comment]
Hi! I don't know much about Caddy, but I know HAProxy can route such proxy connections as regular HTTP requests. Not sure if Caddy is able to handle CONNECT method properly. But also Caddy has its own proxy module, so may be you'd better of with this: https://github.com/caddyserver/forwardproxy

**Comment by Snawoot** [comment]
I see you already commented the [issue](https://github.com/traefik/traefik/issues/9708) regarding CONNECT method in Traefik. It seems people already have exactly the same issue trying to proxy to Squid, so I don't really expect it to work.

But HAProxy is definitely the way. Probably for your case you'd want to use TCP mode instead and snoop domain from SNI: https://stackoverflow.com/a/78020598

This way haproxy won't even terminate TLS or parse HTTP, it will route purely on TCP level. There are also other SNI routers like sniproxy around.
