### ISSUE TITLE
Lack of snap deployment documentation

### ISSUE THREAD

**Issue by andre487** [SenseUnit/dumbproxy#59]
It would be great if there were some documentation about deployment from snap package

**Comment by Snawoot** [comment]
Should be as trivial as `snap install dumbproxy`, no? Are there people who use snaps but are not familiar with it?

**Comment by andre487** [comment]
> Should be as trivial as `snap install dumbproxy`, no? Are there people around who use snaps but are not familiar with it?

Basically yes, but the trick is how to launch it as a daemon correctly

**Comment by dafanasiev** [comment]
@andre487 look at shadowsosks-rust: https://github.com/shadowsocks/shadowsocks-rust?tab=readme-ov-file#install-using-snap

all snap-enabled services can configure the same way
