### ISSUE TITLE
Fail2ban rule

### ISSUE THREAD

**Issue by m-kalendarev** [SenseUnit/dumbproxy#62]
Hi! Tried to find any error proxy auth logs but only "POST" log messages appeared. 
How to get wrong auth attempts?

**Comment by Snawoot** [comment]
Hello!

Unfortunately, it doesn't log unsuccessful auth attempts. Should be easy to add logging [somewhere after auth check](https://github.com/SenseUnit/dumbproxy/blob/8d0892ed5d40a48e2620c7aa3059ef6e076a773a/handler.go#L141).
