### ISSUE TITLE
Enabling CORS in dumbroxy

### ISSUE THREAD

**Issue by DTs-dev** [SenseUnit/dumbproxy#64]
Добрый день! 

Ряд сервисов не пропускает сквозные запросы через прокси, от чего в консоли Firefox постоянно ошибки "Cross-Origin Request Blocked". Скажите, как то можно добавить к прокси заголовки "Access-Control-Allow-*" ? Или, быть может использовать nginx как доп. прослойку для этого? Но тогда, вероятнее всего, dumbproxy придется запускать как обычный plain proxy, а уже nginx настраивать через https. Можете что-то посоветовать, чтобы избавиться от подобных ошибок? Из-за этого очень сильно замедляется работа с некоторыми сервисами. Заранее благодарю за ответ!

**Comment by Snawoot** [comment]
> Ряд сервисов не пропускает сквозные запросы через прокси

Сервис не знает, через прокси вы с ним работаете или нет. Если у вас проблема с CORS, с dumbproxy она точно не связана. По изменению заголовков ничего сказать не могу. Если у сайта используется HTTPS, то там без mitmproxy вообще ничего поменять не удастся.
