### ISSUE TITLE
Помогите разобраться - "Sorry, our service is currently not available in your region"

### ISSUE THREAD

**Issue by vshaev** [SenseUnit/dumbproxy#66]
Здравствуйте.
Физически я в России. dumbproxy на vps а Нидерландах. Давно  периодически пользуюсь без проблем. Кроме одного случая. При попытке соединения с dl.grafana.com получаю - Sorry, our service is currently not available in your region.
ip адрес сервера проверил -  Нидерланды. Доменное имя с freemyip.com.  На другом vps тоже в Нидерландах установлен outline сервер. Через него без проблем. Как это объяснить и что можно предпринять?

**Comment by scipe** [comment]
Скорее всего твой адрес в блеклисте. Тут можно проверить: https://www.ipqualityscore.com/ 
Другому серверу повезло больше.

**Comment by vshaev** [comment]
> Скорее всего твой адрес в блеклисте. Тут можно проверить: https://www.ipqualityscore.com/ Другому серверу повезло больше.

Проверил.  Всё норм...

**Comment by Snawoot** [comment]
Не думаю, что это имеет отношение к самой программе.

**Comment by vshaev** [comment]
Извините что вовремя не отписался.   Дело в том, что некоторые ресурсы ( но далеко не все) ip сервера определяли как латвийский. А графана этот регион не обслуживает и некоторые их ресурсы там не доступны.
Для себя я нашел выход - dumbproxy переустановил на другой сервер другого провайдера в той же локации.
Но для меня все равно непонятно -  на этот установил amnezia и проблемный ресурс работает... Теперь пытаюсь вспомнить, какой ресурс определял адрес как латвийский)))) 
Спасибо за программу и участие.
