### ISSUE TITLE
При запуске подключает только IP6, IP4 не прослушивается.

### ISSUE THREAD

**Issue by jan-pona** [SenseUnit/dumbproxy#69]
При запуске подключает только IP6, IP4 не прослушивается.
Смотрю в Netstat только ::8080. Хотя остальные сервисы стартуют на обоих протоколах.

**Comment by Snawoot** [comment]
Здравствуйте!

Я проверил только что и вижу, что по умолчанию порт слушает оба протокола:

```
user@ws:~> curl -x [::1]:8080 httpbin.org/headers
{
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/8.10.1", 
    "X-Amzn-Trace-Id": "Root=1-67041504-3eb5f5a4416357f3200f7e0d"
  }
}
user@ws:~> curl -x 127.0.0.1:8080 httpbin.org/headers
{
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/8.10.1", 
    "X-Amzn-Trace-Id": "Root=1-67041557-328125dd2522251a4e7abfc3"
  }
}
```

Какие параметры для запуска вы используете и какую ОС?

**Comment by jan-pona** [comment]
Да, все работает. Ошибка была с моей стороны. 
А вопрос возник потому, что netstat -lpnt показывал, что слушается только tcp6, а на  tcp порт не открыт.
-bind-address '0.0.0.0:443'
Ubuntu 18.04.6 LTS
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::443                  :::*                    LISTEN      7935/dumbproxy
```

**Comment by Snawoot** [comment]
> -bind-address '0.0.0.0:8080'

Я думаю можно вписать просто `-bind-address :8080` и будет такой же результат. Он биндит dual stack IPv6 сокет, поэтому видимо и показывает только IPv6.
