### ISSUE TITLE
flag provided but not defined (docker)

### ISSUE THREAD

**Issue by IvanBye** [SenseUnit/dumbproxy#81]
здравствуйте, использую докер для запуска 
при попытке добавить больше опций в compose (-autocert-email -autocert-http -proxy), контейнер завершается с ошибкой:

flag provided but not defined: (-proxy http:///.......... -autocert-email ...... -autocert-http ...........)
Usage of /dumbproxy:
  -auth string
        auth parameters (default "none://")...........

<details>
<summary>мой compose.yaml:</summary>

version: "3"

services:
  dumbproxy:
    container_name: dumbproxy
    image: ghcr.io/senseunit/dumbproxy:latest
    ports:
      - 8443:8443
      - 8222:80
    command:
      - -bind-address=:8443
      - -auth=static://?username=1&password=2
      - -autocert
      - -autocert-email ok@ok.ok
      - -autocert-http :80
      - -proxy http://172.17.0.1:8118
    volumes:
      - /mnt/cache/appdata/dumbproxy:/.dumbproxy
networks: {}
</details>

**Comment by Snawoot** [comment]
Здравствуйте!

Аргументы должны быть либо одной строкой со значением отделённым через `=`, либо двумя разными строками. Т.е. правильно:

```yaml
- -proxy=http://172.17.0.1.8118
```

либо

```yaml
- -proxy
- http://172.17.0.1.8118
```

но не как у вас через пробел.
