### ISSUE TITLE
Не выводит окно с базовой авторизацией при указанном флаге -auth

### ISSUE THREAD

**Issue by D1maD1m0nd** [SenseUnit/dumbproxy#88]
Привет, занимаюсь настройки dumbproxy **1.13.2**
Сделал все как по документации и зарегистрировал сервис
Вот опции , с которыми я запустил  процесс

> dumbproxy -auth static://?username=examplelogin&password=examplepass -autocert -bind-address :443 

Соответственно переходя через браузер с включенным прокси я вижу  **ERR_UNEXPECTED_PROXY_AUTH**  без предложения ввода логина и пароля 
что я мог упустить? (если нужна доп инфа могу предоставить)

Без авторизации все работает отлично

**Comment by Snawoot** [comment]
> Соответственно переходя через браузер с включенным прокси я вижу **ERR_UNEXPECTED_PROXY_AUTH** без предложения ввода логина и пароля
> что я мог упустить?

А как сделана настройка в браузере? Через что? Через настройки прокси в системе или через браузерное расширение типа SwitchyOmega?

Стоит ли на машине какой-то софт, который может вмешиваться в работу прокси и ставить какой-то свой прокси? Например, антивирусы, файрволы или блокировщики рекламы, которые фильтруют все соединения.

Работает ли прокси с логином и паролем если проверять его через curl?

```sh
curl -x https://USERNAME:PASSWORD@DOMAIN https://api.ipify.org ; echo
```

**Comment by D1maD1m0nd** [comment]
Привет

> А как сделана настройка в браузере?

Привет, настройку прокси делал через настройки сети windows(в графе прокси-сервер)


> Стоит ли на машине какой-то софт, который может вмешиваться в работу прокси и ставить какой-то свой прокси?

Нет, на клиенте не стоит доп прокси максимум рабочие впн, но они во время использования прокси отключены. Сам прокси крутится на голой линукс машине. Файрвол отключен и антивирусов нету, блокировщик рекламы стоит, но я пробовал разные браузеры и проверял через инкогнито


> ```shell
> curl -x https://USERNAME:PASSWORD@DOMAIN https://api.ipify.org ; echo
> ```

да, в таком случае команда выводит ip адрес сервера

Хочу отметить, что без этого флага auth все работает ок, и прокси отрабатывает корректно

**Comment by Snawoot** [comment]
> да, в таком случае команда выводит ip адрес сервера

Ну значит тут что-то не то с браузером(-ами), он не должен так реагировать. Очевидно, если в curl-е всё работает, а в браузерах нет, то проблема не в прокси.

> настройку прокси делал через настройки сети windows(в графе прокси-сервер)

Давайте тогда посмотрим скриншот конфигурации прокси в системе с замазанным доменом.

Если с фиксом совсем не выйдет, то как вариант можно запустить dumbproxy ещё и на клиенте:

```
dumbproxy -bind-address 127.0.0.1:8080 -proxy https://USERNAME:PASSWORD@DOMAIN
```

где https://USERNAME:PASSWORD@DOMAIN -- адрес и логин-пароль самой прокси. Тогда локально запустится прокся без авторизации, которая будет пересылать всё на прокси на удалённом сервере.
